name: Devops-pipeline

on:
  push:
    branches: [ "De25-ms" ]
  workflow_dispatch:
    inputs:
      log_errors:
        description: "Logga fel som artefakt?"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "COINMARKET_API_KEY=${{ secrets.COINMARKET_API_KEY }}" >> .env
          echo "COINMARKETCAP_SYMBOLS=${{ secrets.COINMARKETCAP_SYMBOLS }}" >> .env
          echo "UPDATE_FREQ_SEC=${{ secrets.UPDATE_FREQ_SEC }}" >> .env

      - name: Unit and integration test
        run: |
          pytest tests/test_crypto_api.py || (echo "Tester misslyckades, se detaljer nedan:" > error.log && pytest tests/test_crypto_api.py >> error.log 2>&1)

  log_errors:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ needs.test.result == 'failure' && github.event.inputs.log_errors == 'true' }}
    steps:
      - name: Upload error log
        uses: actions/upload-artifact@v4
        with:
          name: error-log
          path: error.log

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mas1344/app-dashboard
      IMAGE_TAG: latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build . --tag $IMAGE_NAME:$IMAGE_TAG

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
